spring:
  profiles:
    active: local-tortoise
  application:
    name: business-gateway
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露端点，这样actuator就可以监控的到健康状况
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
